name: Beispiel Workflow

on:
  push:
    branches:
      - main

jobs:
  step_a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: step A
        run: echo "Dies ist Step A"

  step_b:
    runs-on: ubuntu-latest
    needs: step_a
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Job B - Ausgabe einer Nachricht
        run: echo "Dies ist Step B"

  step_c:
    runs-on: ubuntu-latest
    needs: step_b
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Step C - Ausgabe einer Nachricht
        run: echo "Dies ist Step C"
